name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ghc: ['9.6']

    steps:
      - uses: actions/checkout@v3

      - uses: haskell/actions/setup@v2
        id: setup-haskell
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Freeze dependencies
        run: cabal freeze

      - uses: actions/cache@v3
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: build-${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            build-${{ runner.os }}-${{ matrix.ghc }}-

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libx11-dev libxft-dev libxinerama-dev libxrandr-dev libxss-dev

      - name: Install a xmonad command
        run: cabal install --overwrite-policy=always --jobs xmonad

      - name: Deploy the xmonad config
        run: |
          mkdir -p ~/.config
          ln -s "$PWD" ~/.config/xmonad

      - name: Build my xmonad executable
        run: xmonad --recompile

  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run ormolu
        uses: mrkkrp/ormolu-action@v11

  cabal-format:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ghc: ['9.6']

    steps:
      - uses: actions/checkout@v3

      - uses: haskell/actions/setup@v2
        id: setup-haskell
        with:
          ghc-version: ${{ matrix.ghc }}

      - uses: actions/cache@v3
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: format-${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project') }}
          restore-keys: |
            format-${{ runner.os }}-${{ matrix.ghc }}-

      - name: Install cabal-fmt
        run: cabal install --overwrite-policy=always -j cabal-fmt

      - name: Run cabal-fmt
        run: diff -y xmonad-config.cabal <(cabal-fmt xmonad-config.cabal)

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: haskell/actions/hlint-setup@v2
        with:
          version: '3.8'

      - uses: haskell/actions/hlint-run@v2
        with:
          fail-on: status
          path: '["app/"]'

  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ludeeus/action-shellcheck@master
        with:
          scandir: bin
          additional_files: build xcapture

  actionlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run actionlint
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color
