name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run ormolu
        uses: mrkkrp/ormolu-action@v6

  cabal-format:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ghc: ['8.10.7']
        cabal: ['3.6.2.0']

    steps:
      - uses: actions/checkout@v3

      - uses: haskell/actions/setup@v2
        id: setup-haskell
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - uses: actions/cache@v3
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: format-${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project') }}
          restore-keys: |
            format-${{ runner.os }}-${{ matrix.ghc }}-

      - name: Add path
        run: echo ~/.cabal/bin >> "$GITHUB_PATH"

      - name: Install cabal-fmt
        run: cabal install --overwrite-policy=always -j cabal-fmt

      - name: Run cabal-fmt
        run: diff -y xmonad-config.cabal <(cabal-fmt xmonad-config.cabal)

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: haskell/actions/hlint-setup@v2
        with:
          version: '3.4'

      - uses: haskell/actions/hlint-run@v2
        with:
          fail-on: status
          path: '["app/"]'

  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ludeeus/action-shellcheck@master
        with:
          scandir: bin
          additional_files: build xcapture

  actionlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run actionlint
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color
